a=int(input("enter a:"))
b=int(input("enter b:"))
print("addition :", a+b)
print("substraction:", a-b)
print("multiplication:", a*b)
print("exponential:", a**b)
print("division:", a/b if b!=0  else 'not defined')
print("modulus:", a%b if b!=0  else 'not defined')
print("floor division:", a//b if b!=0  else 'not defined')
