a=int(input("enter a:"))
b=int(input("enter b:"))
print("addition :", a+b)
print("substraction:", a-b)
print("multiplication:", a*b)
print("exponential:", a**b)
print("division:", a/b)
print("modulus:", a%b)
print("floor division:", a//b)
print('Happy Calculating.')
